### ISSUE TITLE
The link points to an empty list

### ISSUE THREAD

**Issue by egonw** [biohackrxiv/preview.biohackrxiv.org#23]
https://github.com/biohackrxiv/preview.biohackrxiv.org/blob/51714a302b9713685020cd3b547a6bf19482a174/views/index.slim#L25

Maybe https://biohackrxiv.org/discover can be used instead, but the `.json` link just below that may not have an equivalent.

**Comment by inutano** [comment]
This is perhaps because Pjotr's server is down @pjotrp 
We may have to have both of them and show a message if the list is not shown correctly

**Comment by pjotrp** [comment]
Please point the list to 

https://osf.io/preprints/biohackrxiv/discover?q=

for now. We can't maintain the list because of a lack of metadata and
we are working on that.

**Comment by inutano** [comment]
made a PR to fix this https://github.com/biohackrxiv/preview.biohackrxiv.org/pull/24
